[cov-col-list]
sex,age,total_counts

[sample-cov-col-list]
sex,age

[pheno-col]
y

[trait-type]
count

[skip-vre]
FALSE

[pheno-remove-zeros]
FALSE

[use-sparse-grm-null]
FALSE

[use-grm-null]
FALSE

[is-cov-offset]
FALSE

[is-cov-transform]
TRUE

[skip-model-fitting]
FALSE

[tol]
0.00001

[is-overwrite-vre-file]
TRUE

[min-maf]
0

[min-mac]
5
