[saige]
# principal arguments
celltypes = ['CD4_TCM']
chromosomes = ['chr21']
drop_genes =[]

# secondary arguments
max_parallel_jobs = 350
cis_window_size = 100000
# these args are applied directly to step1_fitNULLGLMM_qtl.R
# as "--{key}={value} "
[saige.build_fit_null]
covarColList = 'sex,age,geno_PC1,geno_PC2,geno_PC3,geno_PC4,geno_PC5,harmony_PC1,harmony_PC2,harmony_PC3,harmony_PC4,harmony_PC5,BioHEART'
sampleCovarColList = 'sex,age,geno_PC1,geno_PC2,geno_PC3,geno_PC4,geno_PC5'
sampleIDColinphenoFile = 'individual'
# Poisson, count_nb = Negative Binomial, quantitative = Normal
traitType = 'count'

# option to skip Variance Ratio estimation (discouraged)
skipVarianceRatioEstimation = 'FALSE'
isRemoveZerosinPheno = 'FALSE'
useSparseGRMtoFitNULL = 'FALSE'
useGRMtoFitNULL = 'FALSE'
# option to treat fixed covariates as offset
isCovariateOffset = 'FALSE'
# option to transform (scale) covariates
isCovariateTransform = 'TRUE'
# option to skip model fitting (discouraged)
skipModelFitting = 'FALSE'
# tolerance for convergence
tol = 0.00001
# max iterations (increase if it fails to converge)
maxiterPCG = 5000
IsOverwriteVarianceRatioFile = 'TRUE'
[saige.sv_test]
vcfField = 'GT'
# minimum variant minor allele frequency to include
minMAF = 0
# minimum variant minor allele count to include
minMAC = 5
# leave one chromosome out
LOCO = 'FALSE'
markers_per_chunk = 10000
SPAcutoff = 10000
[saige.set_test]
vcfField = 'GT'
maxMAF_in_groupTest = 0.1
minMAF_in_groupTest_Exclude = 0
annotation_in_groupTest = 'null,test'
MACCutoff_to_CollapseUltraRare = 1
is_single_in_groupTest = 'TRUE'
is_equal_weight_in_groupTest = 'TRUE'
# leave one chromosome out
LOCO = 'FALSE'
markers_per_chunk = 10000
SPAcutoff = 10000
[saige.job_specs.fit_null]
storage = "0G"
memory = "4Gi"
[saige.job_specs.sv_test]
cpu = 1
storage = '25G'
[saige.job_specs.set_test]
cpu = 1
storage = '30G'
