[saige]
# principal arguments
celltypes = ['CD4_TCM']
chromosomes = ['chr1','chr2','chr3','chr4','chr5','chr6','chr7','chr8','chr9','chr10','chr11','chr12','chr13','chr14','chr15','chr16','chr17','chr18','chr19','chr20','chr21','chr22']
drop_genes = ['ENSG00000291100','ENSG00000278996','ENSG00000215386','ENSG00000291100','ENSG00000196421','ENSG00000171858','ENSG00000211679','ENSG00000108298','ENSG00000121101','ENSG00000161970','ENSG00000265681','ENSG00000125744','ENSG00000233927','ENSG00000170889','ENSG00000167618','ENSG00000142541','ENSG00000137959','ENSG00000290122','ENSG00000289474','ENSG00000109321','ENSG00000161055','ENSG00000228716','ENSG00000248874','ENSG00000124762','ENSG00000196376','ENSG00000204388','ENSG00000204389','ENSG00000146918','ENSG00000229618','ENSG00000254349','ENSG00000167114','ENSG00000185532','ENSG00000248905','ENSG00000259345','ENSG00000197943','ENSG00000259692']
# secondary arguments
max_parallel_jobs = 50
cis_window_size = 100000
# these args are applied directly to step1_fitNULLGLMM_qtl.R
# as "--{key}={value} "
[saige.build_fit_null]
covarColList = 'sex,age,geno_PC1,geno_PC2,geno_PC3,geno_PC4,geno_PC5,geno_PC6,geno_PC7,PC1,PC2,PC3,PC4,PC5,BioHEART,total_counts,pct_counts_mt'
sampleCovarColList = 'sex,age,geno_PC1,geno_PC2,geno_PC3,geno_PC4,geno_PC5,geno_PC6,geno_PC7'
sampleIDColinphenoFile = 'individual'
# Poisson, count_nb = Negative Binomial, quantitative = Normal
traitType = 'count'

# option to skip Variance Ratio estimation (discouraged)
skipVarianceRatioEstimation = 'FALSE'
isRemoveZerosinPheno = 'FALSE'
useSparseGRMtoFitNULL = 'FALSE'
useGRMtoFitNULL = 'FALSE'
# option to treat fixed covariates as offset
isCovariateOffset = 'FALSE'
# option to transform (scale) covariates
isCovariateTransform = 'TRUE'
# option to skip model fitting (discouraged)
skipModelFitting = 'FALSE'
# tolerance for convergence
tol = 0.00001
# max iterations (increase if it fails to converge)
maxiterPCG = 5000
IsOverwriteVarianceRatioFile = 'TRUE'
[saige.sv_test]
vcfField = 'GT'
# minimum variant minor allele frequency to include
minMAF = 0
# minimum variant minor allele count to include
minMAC = 5
# leave one chromosome out
LOCO = 'FALSE'
markers_per_chunk = 10000
SPAcutoff = 10000
[saige.set_test]
vcfField = 'GT'
maxMAF_in_groupTest = 0.01
minMAF_in_groupTest_Exclude = 0
annotation_in_groupTest = 'null'
MACCutoff_to_CollapseUltraRare = 1
is_single_in_groupTest = 'TRUE'
is_equal_weight_in_groupTest = 'TRUE'
# leave one chromosome out
LOCO = 'FALSE'
markers_per_chunk = 10000
SPAcutoff = 10000
[saige.job_specs.fit_null]
storage = "0G"
memory = "25G"
[saige.job_specs.sv_test]
cpu = 1
storage = '25G'
[saige.job_specs.set_test]
cpu = 1
storage = '30G'
memory = "80G"
